//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace takeda.bizagi.connector.BizAgiCacheWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CacheSoap", Namespace="http://tempuri.org/")]
    public partial class Cache : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CleanUpCacheEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CleanUpCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback cleanUpRuleCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback FreeLocalizationResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CleanRenderCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback cleanParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback CleanTracingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePortalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Cache() {
            this.Url = global::takeda.bizagi.connector.Properties.Settings.Default.BizAgiConnectorLibrary_BizAgiCacheWebservice_Cache;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CleanUpCacheEntriesCompletedEventHandler CleanUpCacheEntriesCompleted;
        
        /// <remarks/>
        public event CleanUpCacheCompletedEventHandler CleanUpCacheCompleted;
        
        /// <remarks/>
        public event cleanUpRuleCacheCompletedEventHandler cleanUpRuleCacheCompleted;
        
        /// <remarks/>
        public event FreeLocalizationResourcesCompletedEventHandler FreeLocalizationResourcesCompleted;
        
        /// <remarks/>
        public event CleanRenderCacheCompletedEventHandler CleanRenderCacheCompleted;
        
        /// <remarks/>
        public event cleanParametersCompletedEventHandler cleanParametersCompleted;
        
        /// <remarks/>
        public event CleanTracingCompletedEventHandler CleanTracingCompleted;
        
        /// <remarks/>
        public event UpdatePortalCompletedEventHandler UpdatePortalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CleanUpCacheEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CleanUpCacheEntries(CacheEntry[] entries) {
            this.Invoke("CleanUpCacheEntries", new object[] {
                        entries});
        }
        
        /// <remarks/>
        public void CleanUpCacheEntriesAsync(CacheEntry[] entries) {
            this.CleanUpCacheEntriesAsync(entries, null);
        }
        
        /// <remarks/>
        public void CleanUpCacheEntriesAsync(CacheEntry[] entries, object userState) {
            if ((this.CleanUpCacheEntriesOperationCompleted == null)) {
                this.CleanUpCacheEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCleanUpCacheEntriesOperationCompleted);
            }
            this.InvokeAsync("CleanUpCacheEntries", new object[] {
                        entries}, this.CleanUpCacheEntriesOperationCompleted, userState);
        }
        
        private void OnCleanUpCacheEntriesOperationCompleted(object arg) {
            if ((this.CleanUpCacheEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CleanUpCacheEntriesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CleanUpCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CleanUpCache(string sPrefix, string sKey) {
            this.Invoke("CleanUpCache", new object[] {
                        sPrefix,
                        sKey});
        }
        
        /// <remarks/>
        public void CleanUpCacheAsync(string sPrefix, string sKey) {
            this.CleanUpCacheAsync(sPrefix, sKey, null);
        }
        
        /// <remarks/>
        public void CleanUpCacheAsync(string sPrefix, string sKey, object userState) {
            if ((this.CleanUpCacheOperationCompleted == null)) {
                this.CleanUpCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCleanUpCacheOperationCompleted);
            }
            this.InvokeAsync("CleanUpCache", new object[] {
                        sPrefix,
                        sKey}, this.CleanUpCacheOperationCompleted, userState);
        }
        
        private void OnCleanUpCacheOperationCompleted(object arg) {
            if ((this.CleanUpCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CleanUpCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cleanUpRuleCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cleanUpRuleCache() {
            object[] results = this.Invoke("cleanUpRuleCache", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cleanUpRuleCacheAsync() {
            this.cleanUpRuleCacheAsync(null);
        }
        
        /// <remarks/>
        public void cleanUpRuleCacheAsync(object userState) {
            if ((this.cleanUpRuleCacheOperationCompleted == null)) {
                this.cleanUpRuleCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OncleanUpRuleCacheOperationCompleted);
            }
            this.InvokeAsync("cleanUpRuleCache", new object[0], this.cleanUpRuleCacheOperationCompleted, userState);
        }
        
        private void OncleanUpRuleCacheOperationCompleted(object arg) {
            if ((this.cleanUpRuleCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cleanUpRuleCacheCompleted(this, new cleanUpRuleCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FreeLocalizationResources", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FreeLocalizationResources() {
            this.Invoke("FreeLocalizationResources", new object[0]);
        }
        
        /// <remarks/>
        public void FreeLocalizationResourcesAsync() {
            this.FreeLocalizationResourcesAsync(null);
        }
        
        /// <remarks/>
        public void FreeLocalizationResourcesAsync(object userState) {
            if ((this.FreeLocalizationResourcesOperationCompleted == null)) {
                this.FreeLocalizationResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFreeLocalizationResourcesOperationCompleted);
            }
            this.InvokeAsync("FreeLocalizationResources", new object[0], this.FreeLocalizationResourcesOperationCompleted, userState);
        }
        
        private void OnFreeLocalizationResourcesOperationCompleted(object arg) {
            if ((this.FreeLocalizationResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FreeLocalizationResourcesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CleanRenderCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CleanRenderCache() {
            this.Invoke("CleanRenderCache", new object[0]);
        }
        
        /// <remarks/>
        public void CleanRenderCacheAsync() {
            this.CleanRenderCacheAsync(null);
        }
        
        /// <remarks/>
        public void CleanRenderCacheAsync(object userState) {
            if ((this.CleanRenderCacheOperationCompleted == null)) {
                this.CleanRenderCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCleanRenderCacheOperationCompleted);
            }
            this.InvokeAsync("CleanRenderCache", new object[0], this.CleanRenderCacheOperationCompleted, userState);
        }
        
        private void OnCleanRenderCacheOperationCompleted(object arg) {
            if ((this.CleanRenderCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CleanRenderCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cleanParameters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cleanParameters() {
            this.Invoke("cleanParameters", new object[0]);
        }
        
        /// <remarks/>
        public void cleanParametersAsync() {
            this.cleanParametersAsync(null);
        }
        
        /// <remarks/>
        public void cleanParametersAsync(object userState) {
            if ((this.cleanParametersOperationCompleted == null)) {
                this.cleanParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OncleanParametersOperationCompleted);
            }
            this.InvokeAsync("cleanParameters", new object[0], this.cleanParametersOperationCompleted, userState);
        }
        
        private void OncleanParametersOperationCompleted(object arg) {
            if ((this.cleanParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cleanParametersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CleanTracing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CleanTracing() {
            this.Invoke("CleanTracing", new object[0]);
        }
        
        /// <remarks/>
        public void CleanTracingAsync() {
            this.CleanTracingAsync(null);
        }
        
        /// <remarks/>
        public void CleanTracingAsync(object userState) {
            if ((this.CleanTracingOperationCompleted == null)) {
                this.CleanTracingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCleanTracingOperationCompleted);
            }
            this.InvokeAsync("CleanTracing", new object[0], this.CleanTracingOperationCompleted, userState);
        }
        
        private void OnCleanTracingOperationCompleted(object arg) {
            if ((this.CleanTracingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CleanTracingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePortal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePortal() {
            this.Invoke("UpdatePortal", new object[0]);
        }
        
        /// <remarks/>
        public void UpdatePortalAsync() {
            this.UpdatePortalAsync(null);
        }
        
        /// <remarks/>
        public void UpdatePortalAsync(object userState) {
            if ((this.UpdatePortalOperationCompleted == null)) {
                this.UpdatePortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePortalOperationCompleted);
            }
            this.InvokeAsync("UpdatePortal", new object[0], this.UpdatePortalOperationCompleted, userState);
        }
        
        private void OnUpdatePortalOperationCompleted(object arg) {
            if ((this.UpdatePortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePortalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CacheEntry {
        
        private string prefixField;
        
        private string keyField;
        
        /// <remarks/>
        public string prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CleanUpCacheEntriesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CleanUpCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void cleanUpRuleCacheCompletedEventHandler(object sender, cleanUpRuleCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cleanUpRuleCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cleanUpRuleCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void FreeLocalizationResourcesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CleanRenderCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void cleanParametersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CleanTracingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdatePortalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591